### ISSUE TITLE
Forced Migration to Org Level

### ISSUE THREAD

**Issue by jluterek** [commercetools/commercetools-bundles-starter#165]
https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications

**Comment by praveenkumarct** [comment]
@nspeet sure, I will check and create a ticket to work on this task. thank you.

**Comment by praveenkumarct** [comment]
Migrated to Org level and released first public version.
https://github.com/commercetools/commercetools-bundles-starter/releases/tag/v1.0.0
