### ISSUE TITLE
Unable to connect to github.com

### ISSUE THREAD

**Issue by de-burhan** [commercetools/commercetools-bundles-starter#212]
Does the bundle starter include some repo that is private and requires access? I am actually getting an error

I only checkedout the repo and exec following on the root level.

```
yarn
```

which produced the following output

```
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/terkelg/prompts.git
Directory: /Volumes/commercetools/commercetools-bundles-starter/packages/bundles-static
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Operation timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by mato84** [comment]
This is resolve this problem
`git config --global url."https://".insteadOf git://`

**Comment by praveenkumarct** [comment]
> This is resolve this problem
> git config --global url."https://".insteadOf git://
@de-burhan Does this solve your issue?

**Comment by spalfreyman** [comment]
This fixed the same issue for me - looks like git changed the security against the git protocol a while back: https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by praveenkumarct** [comment]
Thank you for confirming. I will close the issue.
