### ISSUE TITLE
Static Bundle Firebase Build Error

### ISSUE THREAD

**Issue by amilges** [commercetools/commercetools-bundles-starter#221]
Link: https://github.com/commercetools/commercetools-bundles-starter/tree/master/packages/bundles-static

I ran into a couple of issue when following the directions.

Issue: Errors are thrown when compiling the firebase html. It is able to compile if I remove the headers and config option but the app doesn't function properly on the price tab.
command: yarn deploy:firebase

Error:
$ cross-env FIREBASE_TARGET=bundles-manager mc-scripts compile-html --headers=C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/production-firebase.headers.json --config=C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/production-firebase.env.json --use-local-assets --transformer C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/config/transformer-firebase.js
C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:404
throw new CACError(Unknown option }}${name.length > 1 ? {{-${name} : ${name}}``);
^

CACError: Unknown option --headers
at Command.checkUnknownOptions (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:404:17)
at CAC.runMatchedCommand (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:602:13)
at CAC.parse (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:541:12)
at Object.run (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules@commercetools-frontend\\mc-scripts\\cli\\dist
commercetools-frontend-mc-scripts-cli.cjs.dev.js:326:7)
at Object.<anonymous> (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules@commercetools-frontend\\mc-scripts\\bin
cli.js:3:51)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Issue: This may be related to the issue above. The links for pricing and display for pricing are showing an error in the deployed application. Also the mcURL is mentioned in the documentation but this is not a configurable option.
Clicking add price has unknown for the URL.

![image](https://user-images.githubusercontent.com/23725598/190189921-10b72d1a-b77b-4901-bc3a-def1b1142a6e.png)

**Comment by johnpduane** [comment]
See also, the comments from @emmenko here: https://github.com/commercetools/merchant-center-application-kit/issues/2803#issuecomment-1246840413

**Comment by nspeet** [comment]
@praveenkumarct As a first step should we remove the headers and config options from any commands in the repo?

**Comment by amilges** [comment]
@praveenkumarct - thank you for taking this issue.  I'm hoping that you were able to review and determine the changes needed.  Let me know if there are any updates or if you have an estimate when you might have a PR that we are able to test.

**Comment by praveenkumarct** [comment]
@amilges 
All the config issues are fixed for both static and dynamic Bundles starter app.
Please check the latest release: https://github.com/commercetools/commercetools-bundles-starter/releases/tag/v1.1.0

This issue shouldn't exist anymore. But we have removed the legacy deployment config from the repository. Please find an alternative for deployment examples [here](https://docs.commercetools.com/custom-applications/deployment-examples).
