### ISSUE TITLE
Doc fix for pricing url

### ISSUE THREAD

**Issue by nspeet** [commercetools/commercetools-bundles-starter#222]
Users are having issues adding or changing any price after creating bundle product. When they have tried adding pricing they are redirected to url (sample) https://undefined/project-dev/products/155ec41h-96c1-36df-b462-e2f8fc5f4f7e/variants/1/prices.  Is this as simple as adding the doc on how to config this url?

**Comment by praveenkumarct** [comment]
Fixed and released.
https://github.com/commercetools/commercetools-bundles-starter/releases/tag/v1.1.0
