### ISSUE TITLE
Add Image Button Usage is Broken

### ISSUE THREAD

**Issue by nspeet** [commercetools/commercetools-bundles-starter#223]
Investigate for static bundles "add image using button 'add image' in Images tab is not adding images"

**Comment by nspeet** [comment]
@praveenkumarct I was able to replicate this issue with the Add Image button locally.

**Comment by praveenkumarct** [comment]
Fixed and released.
https://github.com/commercetools/commercetools-bundles-starter/releases/tag/v1.1.0
