### ISSUE TITLE
Deployment issue using vercel

### ISSUE THREAD

**Issue by Saket1511** [commercetools/commercetools-bundles-starter#256]
error Command failed.
--
13:38:46.575 | Exit code: 128
13:38:46.576 | Command: git
13:38:46.576 | Arguments: ls-remote --tags --heads git://github.com/terkelg/prompts.git
13:38:46.576 | Directory: /vercel/path0/packages/bundles-static
13:38:46.576 | Output:
13:38:46.576 | fatal: unable to connect to github.com:
13:38:46.576 | github.com[0: 140.82.112.3]: errno=Connection timed out
13:38:46.576 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
13:38:46.611 | Error: Command "yarn install" exited with 128

it seems we are using the terkelg/prompt package as part of the platform and when yarn tries to pull it in its not been updated to the https url for git (rather than git://)

so thats easy enough to fix locally but vercel doesn't seem to support git config too well

**Comment by praveenkumarct** [comment]
Hello @Saket1511, Could you please give us some more details on the issue?

 - Can you reconfirm the node, yarn versions.
 - Are you able to run application locally.
 - Did this error occur locally for you? If yes, Can you please help us understand how did you solve it to work locally?

**Comment by Saket1511** [comment]
node version-v16.18.0
yarn- 1.22.19
yes, able to run locally
Yes, this error occurred locally too, but resolved by running this command 
`git config --global url."https://".insteadOf git://`

**Comment by Saket1511** [comment]
Please help me resolve this issue as soon as possible.

**Comment by praveenkumarct** [comment]
Hello @Saket1511, 
This is an issue from github and not from Bundles-Starter project.
I am unable to reproduce this error from my system.

As already suggested, Locally this can be resolved like suggested here: https://stackoverflow.com/questions/59963949/error-couldnt-find-match-for-ref-when-running-builds-using-jenkins-slave-usi
https://github.com/yarnpkg/yarn/issues/7239

May be can you check with Vercel support team on this github issue?

**Comment by Saket1511** [comment]
Did you able to deploy this application on vercel?

**Comment by praveenkumarct** [comment]
@emmenko
In Vercel we have issue connecting to github.
Can you check this deployment issue? Let us know if you any suggestions for fixing this issue.
Or do you think we should contact Vercel support for this fix?

**Comment by Saket1511** [comment]
Did you check this deployment with aws s3 bucket & cloud front?

**Comment by praveenkumarct** [comment]
> Did you check this deployment with aws s3 bucket & cloud front?
No, I haven't tried.

If you have any deployment issues, Please check [here](https://docs.commercetools.com/custom-applications/deployment-examples/vercel) or create a support issue as suggested in the documentation.

**Comment by phofmann** [comment]
So, removing the `jest-plugin-filename` in all jest files and in the package.json files and running a yarn install afterwards will solve the issue. Since `jest-plugin-filename` is version 0.0.1 after four years, how about I create a PR to remove it?

**Comment by praveenkumarct** [comment]
@phofmann Thank you. Yes, you can create a PR.
